/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Enrollment = IDL.Record({
  'paymentMethod' : IDL.Text,
  'user' : IDL.Principal,
  'subjectId' : IDL.Nat,
  'enrolledAt' : Time,
  'paymentReference' : IDL.Text,
  'amountInPaise' : IDL.Nat,
});
export const Lead = IDL.Record({
  'interestedSubject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const MeetingLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'platform' : IDL.Text,
  'subjectId' : IDL.Nat,
  'scheduledAt' : Time,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'method' : IDL.Text,
  'userId' : IDL.Principal,
  'reference' : IDL.Text,
  'currency' : IDL.Text,
  'subjectId' : IDL.Nat,
  'timestamp' : Time,
  'amountInPaise' : IDL.Nat,
});
export const VisitorEvent = IDL.Record({
  'scrollDepth' : IDL.Nat,
  'page' : IDL.Text,
  'timestamp' : Time,
  'sessionId' : IDL.Text,
  'eventType' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FeeOption = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'months' : IDL.Nat,
  'amountInPaise' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const UpiConfig = IDL.Record({
  'displayName' : IDL.Text,
  'upiId' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMeetingLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, Time],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkEnrollment' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'confirmUpiPayment' : IDL.Func([IDL.Nat], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteMeetingLink' : IDL.Func([IDL.Nat], [], []),
  'enroll' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getAllEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllMeetingLinks' : IDL.Func([], [IDL.Vec(MeetingLink)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getAllVisitorEvents' : IDL.Func([], [IDL.Vec(VisitorEvent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeeOptions' : IDL.Func([], [IDL.Vec(FeeOption)], ['query']),
  'getMeetingLinksForSubject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MeetingLink)],
      ['query'],
    ),
  'getMyEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getRazorpayKeyId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getStudentMeetingLinks' : IDL.Func([], [IDL.Vec(MeetingLink)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getUpiConfig' : IDL.Func([], [IDL.Opt(UpiConfig)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPayment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRazorpayConfig' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setUpiConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'trackVisitor' : IDL.Func([VisitorEvent], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Enrollment = IDL.Record({
    'paymentMethod' : IDL.Text,
    'user' : IDL.Principal,
    'subjectId' : IDL.Nat,
    'enrolledAt' : Time,
    'paymentReference' : IDL.Text,
    'amountInPaise' : IDL.Nat,
  });
  const Lead = IDL.Record({
    'interestedSubject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const MeetingLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'platform' : IDL.Text,
    'subjectId' : IDL.Nat,
    'scheduledAt' : Time,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'method' : IDL.Text,
    'userId' : IDL.Principal,
    'reference' : IDL.Text,
    'currency' : IDL.Text,
    'subjectId' : IDL.Nat,
    'timestamp' : Time,
    'amountInPaise' : IDL.Nat,
  });
  const VisitorEvent = IDL.Record({
    'scrollDepth' : IDL.Nat,
    'page' : IDL.Text,
    'timestamp' : Time,
    'sessionId' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FeeOption = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'months' : IDL.Nat,
    'amountInPaise' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const UpiConfig = IDL.Record({
    'displayName' : IDL.Text,
    'upiId' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMeetingLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, Time],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkEnrollment' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'confirmUpiPayment' : IDL.Func([IDL.Nat], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteMeetingLink' : IDL.Func([IDL.Nat], [], []),
    'enroll' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'getAllEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllMeetingLinks' : IDL.Func([], [IDL.Vec(MeetingLink)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getAllVisitorEvents' : IDL.Func([], [IDL.Vec(VisitorEvent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeeOptions' : IDL.Func([], [IDL.Vec(FeeOption)], ['query']),
    'getMeetingLinksForSubject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MeetingLink)],
        ['query'],
      ),
    'getMyEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getRazorpayKeyId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getStudentMeetingLinks' : IDL.Func([], [IDL.Vec(MeetingLink)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getUpiConfig' : IDL.Func([], [IDL.Opt(UpiConfig)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPayment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRazorpayConfig' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setUpiConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'trackVisitor' : IDL.Func([VisitorEvent], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };