/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Enrollment {
  'paymentMethod' : string,
  'user' : Principal,
  'subjectId' : bigint,
  'enrolledAt' : Time,
  'paymentReference' : string,
  'amountInPaise' : bigint,
}
export interface FeeOption {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'months' : bigint,
  'amountInPaise' : bigint,
}
export interface Lead {
  'interestedSubject' : string,
  'name' : string,
  'email' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface MeetingLink {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'createdAt' : Time,
  'platform' : string,
  'subjectId' : bigint,
  'scheduledAt' : Time,
}
export interface PaymentRecord {
  'id' : bigint,
  'status' : string,
  'method' : string,
  'userId' : Principal,
  'reference' : string,
  'currency' : string,
  'subjectId' : bigint,
  'timestamp' : Time,
  'amountInPaise' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subject {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpiConfig { 'displayName' : string, 'upiId' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitorEvent {
  'scrollDepth' : bigint,
  'page' : string,
  'timestamp' : Time,
  'sessionId' : string,
  'eventType' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMeetingLink' : ActorMethod<
    [string, string, bigint, string, Time],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkEnrollment' : ActorMethod<[bigint], boolean>,
  'confirmUpiPayment' : ActorMethod<[bigint], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteMeetingLink' : ActorMethod<[bigint], undefined>,
  'enroll' : ActorMethod<[bigint, string, string, bigint], undefined>,
  'getAllEnrollments' : ActorMethod<[], Array<Enrollment>>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getAllMeetingLinks' : ActorMethod<[], Array<MeetingLink>>,
  'getAllPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'getAllVisitorEvents' : ActorMethod<[], Array<VisitorEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeeOptions' : ActorMethod<[], Array<FeeOption>>,
  'getMeetingLinksForSubject' : ActorMethod<[bigint], Array<MeetingLink>>,
  'getMyEnrollments' : ActorMethod<[], Array<Enrollment>>,
  'getMyPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'getRazorpayKeyId' : ActorMethod<[], [] | [string]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getStudentMeetingLinks' : ActorMethod<[], Array<MeetingLink>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getUpiConfig' : ActorMethod<[], [] | [UpiConfig]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'recordPayment' : ActorMethod<[bigint, string, bigint, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setRazorpayConfig' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setUpiConfig' : ActorMethod<[string, string], undefined>,
  'submitLead' : ActorMethod<[string, string, string, string], undefined>,
  'trackVisitor' : ActorMethod<[VisitorEvent], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];